name: Run Gemini CLI

on:
  workflow_dispatch:  # 수동 실행 트리거

jobs:
  run-gemini:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Gemini CLI
        run: npm install -g @google/gemini-cli

      - name: Run Gemini CLI
        run: echo "Generate 10 Korean names with random ages" | gemini
