name: Run Gemini CLI

on:
  workflow_dispatch:  # 수동 실행 트리거

jobs:
  run-gemini:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Gemini CLI
        run: npm install -g @google/gemini-cli

      - name: Create locales directory inside src
        run: mkdir -p test-project/src/locales

      - name: Run Gemini CLI
        run: echo "I want to extract UI text from my TSX files and generate i18n key-value pairs in English, Korean, Japanese in JSON format " | gemini > test-project/src/locales/generated.json
        env:
         GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

#      - name: Split JSON into locale files
#        run: |
#          jq '.en' test-project/src/locales/generated.json > test-project/src/locales/en.json
#          jq '.ko' test-project/src/locales/generated.json > test-project/src/locales/ko.json
#          jq '.ja' test-project/src/locales/generated.json > test-project/src/locales/ja.json

