name: Run Gemini CLI

on:
  workflow_dispatch:  # 수동 실행 트리거

jobs:
  run-gemini:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Gemini CLI
        run: npm install -g @google/gemini-cli

      - name: Run Gemini CLI
        run: echo "I want to extract UI text from my TSX files and generate i18n key-value pairs in English, Korean, Japanese in JSON format " | gemini > locales/generated.json
        env:
         GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Split JSON into locale files
        run: |
          jq '.ko' locales/generated.json > locales/en.json
          jq '.ja' locales/generated.json > locales/ko.json
          jq '.zh' locales/generated.json > locales/ja.json
